### PR TITLE
Better link CSRF protection

### PR DESCRIPTION
**Pull request by mrtnzlml**
Cc @enumag, what do you think?

related to the #26

### CODE REVIEW

**Comment by enumag** [comment]
@mrtnzlml The `@param` annotation is kind of useless (unless there is a type). As for CSRF protection, that should be fine.

**Comment by mrtnzlml** [comment]
Yeah, it's generated annotation (IDE), not that important. I'll wait for the AOP PR then.

**Comment by enumag** [comment]
Well we will need a PR for Annotations as well imho. ;-)

**Comment by enumag** [comment]
Well we will need a PR for Annotations as well imho. ;-)

**Pull request merged**
